### ISSUE TITLE
Test Issue #2

### ISSUE THREAD

**Issue by Link-** [Link-/gh-issues-ltt#2]
### Action Items
- [ ] Action item #10 for @Link- 
- [ ] @Link- has to do action items #12
- [ ] @Link- and @someuser have to work on #13
- [ ] @someuser and @Link- have to work on #14
- [ ] Work on #15 has to be done by @Link- and @someuser
- [ ] 1234567:1234:12 has to be done by @Link- 
- [ ] #actionitem17
- [ ] #11
- [ ] Action item #18 with a https://google.com
- [ ] #13

---

### Some other section
